### ISSUE TITLE
Compiler errors if emacs tmp files exist in shadow build dir

### ISSUE THREAD

**Issue by lsnape** [james-henderson/phoenix#1]
Steps to reproduce:
1. Create a new project using the `phoenix-webapp` template
2. Make a change to app.cljs
3. `lein dev`
   (_boom_)

A portion of the stack trace:

```
Exception in thread "main" clojure.lang.ExceptionInfo: Error in component :cljs-compiler in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :cljs-compiler, :component #phoenix.modules.cljs.CLJSCompiler{:output-dir "target/resources/js/", :modules [{:name :main, :mains #{test-brepl.ui.app}, :dependencies nil}], :source-path "ui-src", :web-context-path "/js", :resource-prefix "js"}, :system #<SystemMap>}, compiling:(/private/var/folders/t3/v7srlkk121v9492zsnydvq0w0000gq/T/form-init4062606913271261954.clj:1:124)
    at clojure.lang.Compiler.load(Compiler.java:7207)

...

Caused by: java.io.FileNotFoundException: /Users/lukesnape/dev/tmp/test-brepl/ui-src/test_brepl/ui/.#app.cljs (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
```

**Comment by jarohen** [comment]
Irritating that Emacs gives backups the same extension as the files it's backing up (rather than, e.g., app.cljs.bak, app.cljs~, etc) - will look into whether shadow-build can be configured to ignore them. 

Having said that, if it is an emacs related bug, Clojure doesn't seem like the right place to fix it!

**Comment by jarohen** [comment]
Could get shadow-build to ignore files starting with a '.' I suppose - they're supposed to be hidden files (at least on *nix)

**Comment by jarohen** [comment]
Also, if it helps, only seems to break if there're unsaved files. When all the files are saved, `(phoenix/reload!)` or `(phoenix/start!)` starts the system successfully
